### ISSUE TITLE
ts.d not found?

### ISSUE THREAD

**Issue by orefalo** [shinokada/svelte-heros#1]
Module '"svelte-heros"' has no exported member 'FingerPrint'. (ts)
        import SingleCheckbox from '$lib/components/forms/SingleCheckbox.svelte';
        import { FingerPrint } from 'svelte-heros';
        import Image from 'svelte-image';

I must be doing something stupid....

**Comment by shinokada** [comment]
Your icon name is wrong. Please see this list, https://github.com/shinokada/svelte-heros/blob/main/icon-names.md

**Comment by orefalo** [comment]
Good catch...

**Comment by orefalo** [comment]
but then... the documentation here is off

**Comment by orefalo** [comment]
thank you!
