### ISSUE TITLE
TypeError: Unknown file extension ".svelte" for /node_modules/.pnpm/svelte-heros@2.0.0/node_modules/svelte-heros/InformationCircleOutline.svelte

### ISSUE THREAD

**Issue by dennismphil** [shinokada/svelte-heros#2]
While running snapshot tests on components including \`svelte-heros\` getting an error

```
TypeError: Unknown file extension ".svelte" for /node_modules/.pnpm/svelte-heros@2.0.0/node_modules/svelte-heros/InformationCircleOutline.svelte
```

Reference: https://github.com/sveltejs/kit/issues/3045

I believe this has to do with adding a `svelte` property to `package.json` similar to  
https://github.com/nolimits4web/atropos/pull/18/files

**Comment by shinokada** [comment]
Please see [this REPL](https://svelte.dev/repl/00431f2266f94162a79a05ad16a980f0?version=3.48.0), it seems no problem.

**Comment by dennismphil** [comment]
It works well in the code, only fails in the test. May be my \`vitest\` configuration is not correct. Ill close this for now and comment with a resolution

**Comment by shinokada** [comment]
Please let me know what was wrong.

**Comment by dennismphil** [comment]
Minimal repro of the issue
https://stackblitz.com/edit/github-zrwj6k-p7zv51?file=components/Hello.svelte

**Comment by dennismphil** [comment]
Related   
mhkeller/layercake#80

**Comment by shinokada** [comment]
I'm not sure why it fails with your vitest config.
I tried a couple of things but I'm not able to find the solution at the moment.

Please let me know if you find the solution.

**Comment by dennismphil** [comment]
Solution:

> You need to use “deps.inline” config options.

[https://github.com/vitest-dev/vitest/issues/1395#issuecomment-1140670262](https://github.com/vitest-dev/vitest/issues/1395#issuecomment-1140670262)

**Comment by shinokada** [comment]
Can you update your example at https://stackblitz.com/edit/github-zrwj6k-p7zv51?file=vitest.config.ts ?

**Comment by dennismphil** [comment]
![](https://user-images.githubusercontent.com/4141366/170989723-fbdfeb88-10ba-40e1-9052-9084c8b680e3.png)

**Comment by dennismphil** [comment]
Done. Updated now.
