### ISSUE TITLE
[BUG]: Solid and outline variants are of different size.

### ISSUE THREAD

**Issue by jjagielka** [shinokada/svelte-heros#5]
### Description of the bug

All `solid` icons are smaller then their counterparts in `outline` variant.
To make them equal size `solid` size must be set to 28 when `outline` size is 24. (Although there's padding issue then.) 

### Steps To Reproduce

```svelte
   <script>
      import * as Heros from 'svelte-heros'
    </script>

    {#each Object.keys(Heros) as comp}
    <li>
      {comp}
      <svelte:component this={Heros[comp]} size="24"></svelte:component>
      <svelte:component this={Heros[comp]} size="24" variation="solid"></svelte:component>
    </li>
    {/each}
```

**Comment by shinokada** [comment]
Thank you for taking time to fill the issue.
As you see in the original [icons](https://heroicons.com/), they are meant to be smaller.
Since it has the `size` prop, users can change it as they wish.

What do you think?

**Comment by shinokada** [comment]
I close the issue for now.
