### ISSUE TITLE
[FEAT]: icon tag doesn't support user-defined css class

### ISSUE THREAD

**Issue by kuchaguangjie** [shinokada/svelte-heros#6]
### Description

Seems the icon tag's `class` property support tailwind css classes, but don't support user-defined class within `<style></style>` part of the same .svelte file.

e.g:
-  `<XCirclex class="my-class" />`  
    this **doesn't** work,
- `<XCircle variation="solid" class="inline ml-10 mr-3 pb-0.5 text-red-500"/>`
    this works.

Not sure how this works, wondering is it possible to support user-defined css class in icon tag's `class` property, thanks.

**Comment by shinokada** [comment]
Use the `global`.
Is this what you want to do? [REPL](https://svelte.dev/repl/feac5f915b9a43009972c1fe0621a899?version=3.49.0)

![image](https://user-images.githubusercontent.com/147320/187857941-35bddf58-5f3c-456b-93af-2e5532a8e0e6.png)

**Comment by kuchaguangjie** [comment]
@shinokada Just tried, seems it doesn't work.

**Comment by kuchaguangjie** [comment]
If I move css class to app.css, and without `:global`, it will work,

but I prefer to keep it in the specific .svelte file, not global, not sure is that possible.

**Comment by kuchaguangjie** [comment]
@shinokada BTW, in my case my `.my-class` use `@apply ;` to apply tailwind classes.
In you example, it use css attribute directly, maybe that's the difference.

**Comment by kuchaguangjie** [comment]
Just did a simple test, even I use your example, it doesn't work ...
Here is my svelte version:
```
  System:
    OS: Linux 5.14 Linux Mint 20.1 (Ulyssa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 9.01 GB / 15.55 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.71 
    @sveltejs/kit: next => 1.0.0-next.460 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.1.0-beta.1 => 3.1.0-beta.1 
```

**Comment by shinokada** [comment]
Any code or REPL?

**Comment by kuchaguangjie** [comment]
I tried again, now it worked ... not sure what went wrong before ... sorry about that.
